import os

CAMERA_ID = input('CAMERA_ID=')
SECURITY_KEY = input('SECURITY_KEY=')
SERVER_URL = input('SERVER_URL=')
DAHUA_CAMERA_URL = input('DAHUA_CAMERA_URL=')
DAHUA_CAMERA_LOGIN = input('DAHUA_CAMERA_LOGIN=')
DAHUA_CAMERA_PASSWORD = input('DAHUA_CAMERA_PASSWORD=')

IMAGE_NAME = 'cam_listener'

command = f'docker run -d --name cam_{CAMERA_ID} \
-e CAMERA_ID={CAMERA_ID} \
-e SECURITY_KEY={SECURITY_KEY} \
-e SERVER_URL={SERVER_URL} \
-e DAHUA_CAMERA_URL={DAHUA_CAMERA_URL} \
-e DAHUA_CAMERA_LOGIN={DAHUA_CAMERA_LOGIN} \
-e DAHUA_CAMERA_PASSWORD={DAHUA_CAMERA_PASSWORD} \
{IMAGE_NAME}'

os.system(command)
